version: "3.9"  # optional since v1.27.0
services:
  app:
    build: ./
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    environment:
      - MEDIA_PATH=/data
    env_file:
      - .env
